apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nt7tr5s5j-dotnet-basic
  janus-idp.io/tekton: nt7tr5s5j-dotnet-basic
  backstage.io/kubernetes-id: nt7tr5s5j-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nt7tr5s5j-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
